/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as MasterpassRouteImport } from './routes/masterpass'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterpassResetRouteImport } from './routes/masterpass.reset'
import { Route as CredentialsNewRouteImport } from './routes/credentials.new'

const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterpassRoute = MasterpassRouteImport.update({
  id: '/masterpass',
  path: '/masterpass',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterpassResetRoute = MasterpassResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => MasterpassRoute,
} as any)
const CredentialsNewRoute = CredentialsNewRouteImport.update({
  id: '/credentials/new',
  path: '/credentials/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/masterpass': typeof MasterpassRouteWithChildren
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/totp': typeof TotpRoute
  '/credentials/new': typeof CredentialsNewRoute
  '/masterpass/reset': typeof MasterpassResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/masterpass': typeof MasterpassRouteWithChildren
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/totp': typeof TotpRoute
  '/credentials/new': typeof CredentialsNewRoute
  '/masterpass/reset': typeof MasterpassResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/masterpass': typeof MasterpassRouteWithChildren
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/totp': typeof TotpRoute
  '/credentials/new': typeof CredentialsNewRoute
  '/masterpass/reset': typeof MasterpassResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/import'
    | '/masterpass'
    | '/overview'
    | '/settings'
    | '/sharing'
    | '/totp'
    | '/credentials/new'
    | '/masterpass/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/import'
    | '/masterpass'
    | '/overview'
    | '/settings'
    | '/sharing'
    | '/totp'
    | '/credentials/new'
    | '/masterpass/reset'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/import'
    | '/masterpass'
    | '/overview'
    | '/settings'
    | '/sharing'
    | '/totp'
    | '/credentials/new'
    | '/masterpass/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  MasterpassRoute: typeof MasterpassRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  SettingsRoute: typeof SettingsRoute
  SharingRoute: typeof SharingRoute
  TotpRoute: typeof TotpRoute
  CredentialsNewRoute: typeof CredentialsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterpass': {
      id: '/masterpass'
      path: '/masterpass'
      fullPath: '/masterpass'
      preLoaderRoute: typeof MasterpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterpass/reset': {
      id: '/masterpass/reset'
      path: '/reset'
      fullPath: '/masterpass/reset'
      preLoaderRoute: typeof MasterpassResetRouteImport
      parentRoute: typeof MasterpassRoute
    }
    '/credentials/new': {
      id: '/credentials/new'
      path: '/credentials/new'
      fullPath: '/credentials/new'
      preLoaderRoute: typeof CredentialsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MasterpassRouteChildren {
  MasterpassResetRoute: typeof MasterpassResetRoute
}

const MasterpassRouteChildren: MasterpassRouteChildren = {
  MasterpassResetRoute: MasterpassResetRoute,
}

const MasterpassRouteWithChildren = MasterpassRoute._addFileChildren(
  MasterpassRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  MasterpassRoute: MasterpassRouteWithChildren,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
  SharingRoute: SharingRoute,
  TotpRoute: TotpRoute,
  CredentialsNewRoute: CredentialsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
